name: build github
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - github/**
permissions:
  packages: write

jobs:
  push:
    name: "yolks:${{ matrix.github }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        github:
          - action_runner
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./github/${{ matrix.github }}
          file: ./github/${{ matrix.github }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:${{ matrix.github }}
            ${{ github.repository_owner == 'pelican-eggs' && format('ghcr.io/parkervcp/yolks:{0}', matrix.github) || '' }}
